import { Provider } from 'common/provider';
import { ProgressBarProviders } from 'common/provider/progress-bar-provider';
import { PRIMARY_FONT } from 'common/utils/font';
import type { Metadata } from 'next';
import { Toaster } from 'sonner';

import './globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <Provider>
            <html lang="en">
                <body className={PRIMARY_FONT.className}>
                    <ProgressBarProviders>
                        {children}
                        <Toaster />
                    </ProgressBarProviders>
                </body>
            </html>
        </Provider>
    );
}
