import type { Metadata } from 'next';
import { Toaster } from 'sonner';
import { Provider } from 'common/provider';
import { Nunito_Sans } from 'next/font/google';

import './globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const nunitoSans = Nunito_Sans({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <Provider>
            <html lang="en">
                <body className={nunitoSans.className}>
                    {children}
                    <Toaster />
                </body>
            </html>
        </Provider>
    );
}
