import type { Metadata } from 'next';
import { Toaster } from 'sonner';
import { Provider } from 'common/provider';

import './globals.css';
import { PRIMARY_FONT } from 'common/utils/font';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <Provider>
            <html lang="en">
                <body className={PRIMARY_FONT.className}>
                    {children}
                    <Toaster />
                </body>
            </html>
        </Provider>
    );
}
